### PR TITLE
Feature 24 deployment script

### PR DESCRIPTION
**Pull request by pgmvp**
This change is [Reviewable](https://reviewable.io/reviews/pllug/pllug-presentation-system-2/94)

### CODE REVIEW

**Comment by alexchmykhalo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[setup/packages/com.vendor.product/meta/page.ui, line 14 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94#-KOu4RQOe4DCM1QhWBIo:-KOu4RQOe4DCM1QhWBIp:bwghdoq) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/e7dbd93157e6ac04471414d8af7754082a594402/setup/packages/com.vendor.product/meta/page.ui#L14)):_

> ``` XML
>   </property>
>   <property name="windowTitle">
>    <string>Dynamic page example</string>
> ```

Please, set something meaningful for our PPS2 project installer.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94)_

**Comment by alexchmykhalo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

_[setup/packages/com.vendor.product/meta/page.ui, line 14 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94#-KOu4RQOe4DCM1QhWBIo:-KOu5AcjmLIHAWw76D9m:byslge1) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/e7dbd93157e6ac04471414d8af7754082a594402/setup/packages/com.vendor.product/meta/page.ui#L14)):_
<details><summary>

<i>Previously, alexchmykhalo (Alex Chmykhalo) wrote…</i></summary>



> Please, set something meaningful for our PPS2 project installer.
> </details>
> Is it used at all in our installer?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94)_

**Comment by alexchmykhalo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

_[setup/packages/com.vendor.product/meta/package.xml, line 8 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94#-KOu5QnlTyFYFCMq8FvQ:-KOu5QnlTyFYFCMq8FvR:bx6sj1) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/e7dbd93157e6ac04471414d8af7754082a594402/setup/packages/com.vendor.product/meta/package.xml#L8)):_

> ``` XML
>     <ReleaseDate>2010-09-21</ReleaseDate>
>     <Licenses>
>         <License name="Beer Public License Agreement" file="license.txt" />
> ```

Please, use real license - https://github.com/PLLUG/pllug-presentation-system-2/blob/development/LICENSE

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94)_

**Comment by alexchmykhalo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

_[setup/packages/com.vendor.product/meta/license.txt, line 1 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94#-KOu5X4ZvlTlTImSp1Td:-KOu5X4ZvlTlTImSp1Te:b-365s7z) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/e7dbd93157e6ac04471414d8af7754082a594402/setup/packages/com.vendor.product/meta/license.txt#L1)):_

> ```
> Very good license.Do you agree?
> ```

Remove fake license from our sources

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94)_

**Comment by alexchmykhalo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

_[setup/packages/com.vendor.product/meta/installscript.qs, line 39 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94#-KOu5jPp-A4P8SDGWW93:-KOu5jPqaQc244cf9NdV:b2c3eee) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/e7dbd93157e6ac04471414d8af7754082a594402/setup/packages/com.vendor.product/meta/installscript.qs#L39)):_

> ```
>     component.loaded.connect(this, Component.prototype.installerLoaded);
>   installer.setDefaultPageVisible(QInstaller.ComponentSelection, false);
>    // if (!installer.addWizardPage(component, "Page", QInstaller.TargetDirectory))
> ```

Please, remove commented code.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94)_

**Comment by alexchmykhalo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

_[setup/config/config.xml, line 6 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94#-KOu5uoUrwLzDlizDRE2:-KOu5uoUrwLzDlizDRE3:b-8htaev) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/e7dbd93157e6ac04471414d8af7754082a594402/setup/config/config.xml#L6)):_

> ``` XML
>     <Version>1.0.0</Version>
>     <Title>PPS2 Installer</Title>
>     <Publisher>Your vendor</Publisher>
> ```

Set vendor to "PLLUG Community"

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94)_

**Comment by alexchmykhalo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

_[appveyor.yml, line 34 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94#-KOu61sbQxSk80RteKMp:-KOu61scRBYduHs68l5V:b-5q1fme) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/e7dbd93157e6ac04471414d8af7754082a594402/appveyor.yml#L34)):_

> ``` YAML
>     cd %APPVEYOR_BUILD_FOLDER%\pllug-presentation-system 
> 
>     7z a release.7z release\     
> ```

If we have an installer package - we could get rid of the archive.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94)_

**Comment by pgmvp** [comment]
Updated according to review

**Comment by alexchmykhalo** [comment]
Reviewed 3 of 6 files at r2, 1 of 2 files at r3.
Review status: 4 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

_[appveyor.yml, line 34 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94#-KOu61sbQxSk80RteKMp:-KOzA--92qmuQ3P9gMSq:b82g8z1) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/e7dbd93157e6ac04471414d8af7754082a594402/appveyor.yml#L34)):_
<details><summary>

<i>Previously, alexchmykhalo (Alex Chmykhalo) wrote…</i></summary>



> If we have an installer package - we could get rid of the archive.
> </details>
> So what about archive?

---

_[setup/packages/com.vendor.product/meta/package.xml, line 8 [r3]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94#-KOz9rKugOufMQh5PCDx:-KOz9rKugOufMQh5PCDy:bbrk1cg) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/0ffcb1fa3269ff9e7b2c8f5e74991e45f30ee9e5/setup/packages/com.vendor.product/meta/package.xml#L8)):_

> ``` XML
>     <ReleaseDate>2010-09-21</ReleaseDate>
>     <Licenses>
>         <License name="Beer Public License Agreement" file="license.txt" />
> ```

Please, change license name to REAL license name

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/94)_

**Comment by alexchmykhalo** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/PLLUG/pllug-presentation-system-2/pull-request/94/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=PLLUG/pllug-presentation-system-2)

**Pull request merged**
