### PR TITLE
Connected pandoc-slave module to project.

### PR DESCRIPTION
**Pull request by ghost**
This change is [Reviewable](https://reviewable.io/reviews/pllug/pllug-presentation-system-2/90)

### CODE REVIEW

**Comment by Guitarheroua** [comment]
Reviewed 11 of 12 files at r1.
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

_[pllug-presentation-system/presentation-data/slide.cpp, line 62 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/90#-KOk8cGQlmNRYxuVleGC:-KOk8cGQlmNRYxuVleGD:b-22tz0y) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/0d67480c58709c7b444c1dac3efb69cb274a8ce6/pllug-presentation-system/presentation-data/slide.cpp#L62)):_

> ``` cpp
>     if(index >= 0 && index < mElementsList.count())
>     {
>         return mElementsList[index];
> ```

Please, make single return point from method.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/90)_

**Comment by alexchmykhalo** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[pllug-presentation-system/pllug-presentation-system.pro, line 22 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/90#-KOmFaqcnU_uuj_xoUv-:-KOmFaqcnU_uuj_xoUv0:br0nd2c) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/0d67480c58709c7b444c1dac3efb69cb274a8ce6/pllug-presentation-system/pllug-presentation-system.pro#L22)):_

> pandoc-slave/pandoc-slave/pandoc-slave
> Do  we need such a long path? At least 1 "pandoc-slave" is redundant - could we get rid of it?

---

_[pllug-presentation-system/presentation-data/slide.cpp, line 67 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/90#-KOmGG7mrjuUNr9gHPtc:-KOmGG7mrjuUNr9gHPtd:b-xcdjyy) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/0d67480c58709c7b444c1dac3efb69cb274a8ce6/pllug-presentation-system/presentation-data/slide.cpp#L67)):_

> ``` cpp
>     {
>         qWarning() << "Warning: Invalid slide element index.";
>         return new Separator("<hr />");
> ```

If all returns are enclosed inside if blocks - this is a generally bad style, as it is error prone. Too easy forgot to place return if there is few return path in conditionals. Please, make sure, there are at leas 1 default return in the end of function outside of the block.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/90)_

**Comment by Guitarheroua** [comment]
Reviewed 2 of 13 files at r2, 1 of 3 files at r3.
Review status: 13 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

_[pllug-presentation-system/presentation-data/presentation.cpp, line 65 [r3]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/90#-KOsDQdJ3UBqK6QTB58_:-KOsDQdJ3UBqK6QTB58a:b-m0sx64) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/129a300f47ca9b84d0cae138c53f7886f5d9e82b/pllug-presentation-system/presentation-data/presentation.cpp#L65)):_

> ``` cpp
> Slide *Presentation::slide(int index) const
> {
>     Slide *rSlide;
> ```

Please, add `Slide *rSlide {};`, to initialize this pointer with `nullptr`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/90)_

**Comment by Guitarheroua** [comment]
Reviewed 4 of 13 files at r2.
Review status: 17 of 23 files reviewed at latest revision, 5 unresolved discussions.

---

_[pllug-presentation-system/presentation-data/slide.cpp, line 28 [r3]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/90#-KOsM_yFpcAnB-e9p-26:-KOsM_yFpcAnB-e9p-27:b-u667u5) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/129a300f47ca9b84d0cae138c53f7886f5d9e82b/pllug-presentation-system/presentation-data/slide.cpp#L28)):_

>    *this = other;
> This is not guarantee correct copying of object.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/90)_

**Comment by Guitarheroua** [comment]
Review status: 17 of 23 files reviewed at latest revision, 6 unresolved discussions.

---

_[pllug-presentation-system/presentation-data/slide.cpp, line 66 [r3]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/90#-KOsQWQ18nOig1OQo7vq:-KOsQWQ18nOig1OQo7vr:b-3amj5i) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/129a300f47ca9b84d0cae138c53f7886f5d9e82b/pllug-presentation-system/presentation-data/slide.cpp#L66)):_

> ``` cpp
> PresentationElement *Slide::element(int index) const
> {
>     PresentationElement *rElement;
> ```

Please, add `{}` to initialize rElement with `nullptr`

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/90)_

**Comment by Guitarheroua** [comment]
Reviewed 2 of 13 files at r2, 2 of 3 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/90)_

**Comment by Guitarheroua** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/PLLUG/pllug-presentation-system-2/pull-request/90/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=PLLUG/pllug-presentation-system-2)

**Pull request merged**
