### PR TITLE
Slide Preview Screen for PPS.

### PR DESCRIPTION
**Pull request by ghost**
This change is [Reviewable](https://reviewable.io/reviews/pllug/pllug-presentation-system-2/87)

### CODE REVIEW

**Comment by Guitarheroua** [comment]
Reviewed 10 of 33 files at r1.
Review status: 10 of 33 files reviewed at latest revision, 1 unresolved discussion.

---

_[pllug-presentation-system/presentation-data/presentationmodel.cpp, line 80 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87#-KOhtCJN2sgwrgufeJ5U:-KOhtCJN2sgwrgufeJ5V:bqyabrp) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/4361078223c97d85d68bc6c8f7ffb917ea0bc695/pllug-presentation-system/presentation-data/presentationmodel.cpp#L80)):_

> ``` cpp
>         else
>         {
>             return QVariant();
> ```

Please, make one return point from method, and create variable, for example, data, wich will be returned.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87)_

**Comment by Guitarheroua** [comment]
Review status: 10 of 33 files reviewed at latest revision, 2 unresolved discussions.

---

_[pllug-presentation-system/presentation-data/slide.cpp, line 67 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87#-KOhuBR4EzAM85L0gKPk:-KOhuBR58LqLiLMNECsz:b-ovr3ua) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/4361078223c97d85d68bc6c8f7ffb917ea0bc695/pllug-presentation-system/presentation-data/slide.cpp#L67)):_

> ``` cpp
>     {
>         qWarning() << "Warning: Invalid slide element index.";
>         return new Separator("<br />");
> ```

Please, make one return point from method.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87)_

**Comment by Guitarheroua** [comment]
Reviewed 1 of 33 files at r1.
Review status: 11 of 33 files reviewed at latest revision, 2 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87)_

**Comment by Guitarheroua** [comment]
Reviewed 3 of 33 files at r1.
Review status: 14 of 33 files reviewed at latest revision, 3 unresolved discussions.

---

_[pllug-presentation-system/resources/qml/main.qml, line 16 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87#-KOhwEhbDYmnibCub-XA:-KOhwEhcd3Zil5mjn8YK:bs634ow) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/4361078223c97d85d68bc6c8f7ffb917ea0bc695/pllug-presentation-system/resources/qml/main.qml#L16)):_

> ``` QML
> 
>         width: parent.width
>         height: parent.height
> ```

Please, write `anchor.fill: parent` instead of width and height properties.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87)_

**Comment by Guitarheroua** [comment]
Review status: 14 of 33 files reviewed at latest revision, 4 unresolved discussions.

---

_[pllug-presentation-system/resources/qml/TestScreen/Page1.qml, line 10 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87#-KOhwWCPin7mZjPBCd9S:-KOhwWCQA4GgSd5NyKAO:bmh0rkp) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/4361078223c97d85d68bc6c8f7ffb917ea0bc695/pllug-presentation-system/resources/qml/TestScreen/Page1.qml#L10)):_

> ``` QML
>         console.log("Button 2 clicked.");
>     }
> }
> ```

Please, remove TestScreen folder, with all qml elements.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87)_

**Comment by Guitarheroua** [comment]
Reviewed 2 of 33 files at r1.
Review status: 16 of 33 files reviewed at latest revision, 5 unresolved discussions.

---

_[pllug-presentation-system/resources/qml/ToolBarIcons/menu.png, line 0 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87#-KOhwqZRmm9cu7UQwBnE:-KOhwqZRmm9cu7UQwBnF:bb3isa1) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/4361078223c97d85d68bc6c8f7ffb917ea0bc695/pllug-presentation-system/resources/qml/ToolBarIcons/menu.png#L0)):_
Please, remove image resources, as we use FontAwsome instead of images icon.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87)_

**Comment by Guitarheroua** [comment]
Reviewed 1 of 33 files at r1.
Review status: 17 of 33 files reviewed at latest revision, 6 unresolved discussions.

---

_[pllug-presentation-system/resources/qml/View/MainWindow.qml, line 7 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87#-KOhxEjDQHjzCKcYAEhu:-KOhxEjEz6CHkfeIg4Fn:b-qsd32z) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/4361078223c97d85d68bc6c8f7ffb917ea0bc695/pllug-presentation-system/resources/qml/View/MainWindow.qml#L7)):_

> ``` QML
>     id: mainWindow
> 
>     width: parent.width
> ```

Please, remove width property there, as you will set this property outside, where element will be created.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87)_

**Comment by alexchmykhalo** [comment]
Please, make   #include "presentationElement.h" - all letters in LOWER case in   pllug-presentation-system-2/pllug-presentation-system/presentation-data/htmlimport.cpp, as there is compilation error under Linux.

---

Review status: 17 of 33 files reviewed at latest revision, 6 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87#-:-KOmNj0K2gtbAg4mQVfO:b-if42zv)_

**Comment by alexchmykhalo** [comment]
Review status: 17 of 33 files reviewed at latest revision, 8 unresolved discussions.

---

_[pllug-presentation-system/presentation-data/presentationmodel.cpp, line 52 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87#-KOo0L2Vh4b-8q5kzYj-:-KOo0L2Vh4b-8q5kzYj0:bzgr12t) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/4361078223c97d85d68bc6c8f7ffb917ea0bc695/pllug-presentation-system/presentation-data/presentationmodel.cpp#L52)):_

> ``` cpp
>             {
>             // TODO: Implement actions in these cases.
> //            case Roles::X :
> ```

Why do we need to left that roles commented here?

---

_[pllug-presentation-system/presentation-data/presentationmodel.cpp, line 81 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87#-KOo03Dmr8nqihh4VbkN:-KOo03DnHdzzxkw0rdRG:bvwdu8z) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/4361078223c97d85d68bc6c8f7ffb917ea0bc695/pllug-presentation-system/presentation-data/presentationmodel.cpp#L81)):_

> ``` cpp
>         {
>             return QVariant();
>         }
> ```

Please, pay attention to comment above. Add default return path to the end of function body.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87)_

**Comment by alexchmykhalo** [comment]
Reviewed 1 of 33 files at r1.
Review status: 18 of 33 files reviewed at latest revision, 9 unresolved discussions.

---

_[pllug-presentation-system/presentation-data/slide.cpp, line 24 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87#-KOo0ln7ZmjeZzdKBKmU:-KOo0ln8eqi3luAVKkYQ:b-h6stn6) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/4361078223c97d85d68bc6c8f7ffb917ea0bc695/pllug-presentation-system/presentation-data/slide.cpp#L24)):_

> ``` cpp
>  * \brief Copy constructor.
>  */
> Slide::Slide(const Slide &other)
> ```

If copy constructor does nothing - it is better to leave default one

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87)_

**Comment by alexchmykhalo** [comment]
Reviewed 5 of 33 files at r1.
Review status: 20 of 33 files reviewed at latest revision, 10 unresolved discussions.

---

_[pllug-presentation-system/resources/qml/main.qml, line 16 [r1]](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87#-KOok3O6h9fjp-iio9yx:-KOok3O7Ky6nH8LoPwUj:bwtpb3m) ([raw file](https://github.com/pllug/pllug-presentation-system-2/blob/4361078223c97d85d68bc6c8f7ffb917ea0bc695/pllug-presentation-system/resources/qml/main.qml#L16)):_

> ``` QML
> 
>         width: parent.width
>         height: parent.height
> ```

Pay attention to comment above.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/pllug/pllug-presentation-system-2/87)_

**Pull request closed without merging**
